# Generated by Django 6.0.3 on 2026-04-10 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0004_alter_items_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.items')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.carts')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cart', 'item'), name='cart_item_unique')],
            },
        ),
    ]
