# Generated by Django 6.0.3 on 2026-04-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0005_carts_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
